#!/bin/bash

# chkconfig: 345 90 90
# description: Sensu monitoring framework anget

### BEGIN INIT INFO
# Provides:       sensu-agent
# Required-Start: $remote_fs $network
# Required-Stop:  $remote_fs $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Sensu monitoring framework agent
### END INIT INFO

/etc/init.d/sensu-service agent $1

exit $?
